### ISSUE TITLE
Unknown encoder 'libfaac'

### ISSUE THREAD

**Issue by rickmills** [AndyA/psips#1]
Hi, 

Just having a play around with my new Pi Cam and am trying to get your psips script working however am getting Unknown encoder 'libfaac'

I have tried fixing this myself, and even trying alternate codecs but with the same result. Any idea how to correct this? I'm not even bothered about having audio as an option but if I remove the lines referencing audio it breaks the script.

Any info/advice would be greatly appreciated :)

**Comment by guatedude2** [comment]
From the raspberry pi docs: https://www.raspberrypi.org/forums/viewtopic.php?t=45681

```
- Change base=… on line 2 to some directory shared by your http server.
- Change "-c:a libfaac -b:a 128k \" to "-c:a aac -b:a 128k \"
- Change ""live/%08d.ts" < /dev/null" to "-strict 2 "live/%08d.ts" < /dev/null"
```
